name: Keep Backend Warm

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send Keep-Alive Request
        run: |
          curl -s -o /dev/null -w "%{http_code}" https://tripuva-backend-wa.onrender.com/health
